# Generated by Django 3.0.5 on 2020-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('shortAbout', models.CharField(blank=True, max_length=70, null=True)),
                ('marka', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=70, null=True)),
                ('topSpeed', models.IntegerField(blank=True, null=True)),
                ('nm', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('car1', models.ImageField(null=True, upload_to='')),
                ('car2', models.ImageField(null=True, upload_to='')),
                ('car3', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
