# Generated by Django 3.0.5 on 2020-07-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Year'),
        ),
    ]
