# Generated by Django 3.0.5 on 2020-07-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200724_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Year'),
            preserve_default=False,
        ),
    ]
