# Generated by Django 3.0.5 on 2020-07-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200724_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='car5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Year'),
        ),
    ]
