# Generated by Django 3.0.5 on 2020-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200725_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlePrev', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(blank=True, max_length=355, null=True)),
                ('question', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
