# Generated by Django 3.0.5 on 2020-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
