# Generated by Django 3.0.5 on 2020-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='tank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
