# Generated by Django 3.0.5 on 2020-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='additions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
