# Generated by Django 3.0.5 on 2020-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_additions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additions',
            name='date',
        ),
        migrations.AddField(
            model_name='additions',
            name='name',
            field=models.CharField(default=1, max_length=105),
            preserve_default=False,
        ),
    ]
