# Generated by Django 3.0.5 on 2020-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200808_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullFuel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='insurance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
