# Generated by Django 3.0.5 on 2020-08-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_order_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerID',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
