# Generated by Django 3.0.5 on 2020-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_order_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
