# Generated by Django 3.0.5 on 2020-08-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_canceledorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.CharField(blank=True, default='Mercedes', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(blank=True, default='basicUser.jpg', null=True, upload_to=''),
        ),
    ]
